name: build

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ci-${{ github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:16.16.0
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - run: |
          echo "github.ref = ${{ github.ref }}"
          echo "github.sha = ${{ github.sha }}"
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/build
      - uses: actions/cache@v2
        id: build
        with:
          key: build-${{ runner.os }}-${{ github.sha }}
          path: |
            dist

  visual-test:
    needs: [build]
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.24.0-focal
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        id: build
        with:
          key: build-${{ runner.os }}-${{ github.sha }}
          path: |
            dist
      - name: Install Playwright Browsers
        run: yarn playwright install chromium
      - name: test
        run: yarn test
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 2
